### ISSUE TITLE
very low speeds with undocking

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/scitos_apps#153]
I have calibrated the docking, and betty docks normally. However, when i tell her to undock, it seems to start with normal negative speeds, but then it gets veryc close to zero and the robot doesn't move anymore. here is the firt few published velocities:

```
linear: 
  x: -0.5
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0

---
linear: 
  x: -0.5
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0

---
linear: 
  x: -0.5
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0

---
linear: 
  x: -0.5
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0

---
linear: 
  x: -0.00750212669373
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0

---
linear: 
  x: -0.00750212669373
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0

---
linear: 
  x: -0.00750212669373
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0

---
linear: 
  x: -0.00750212669373
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0

---
linear: 
  x: -0.00750212669373
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0
```

It keeps publishing these very slow speeds afterwards.
